### ISSUE TITLE
require "zoo" fail

### ISSUE THREAD

**Issue by andi1991** [ZigzagAK/ngx_zookeeper_lua#1]
2017/12/07 09:56:55 [error] 21121#0: *28 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:70):2: module 'zoo' not found:
	no field package.preload['zoo']
	no file './zoo.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta1/zoo.lua'
	no file '/usr/local/share/lua/5.1/zoo.lua'
	no file '/usr/local/share/lua/5.1/zoo/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/zoo.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/zoo/init.lua'
	no file './zoo.so'
	no file '/usr/local/lib/lua/5.1/zoo.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/zoo.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by ZigzagAK** [comment]
# path to LUA modules
  lua_package_path "lib/?.lua;;lua/?.lua;;";
  lua_package_cpath "lib/lua/5.1/?.so;;";
