### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by hamsbon** [ZigzagAK/ngx_zookeeper_lua#2]
Hi, I had install nginx, lua, etc. But I find out build.sh include the procedure of installation of other software, so I wonder how can I use this module without those installations.
Thank you.

**Comment by ZigzagAK** [comment]
@hamsbon 
Simple way to use this module is using build.sh script. You may modify it and remove PCRE, ZLIB dependencies (use system). You may build this module as dynamic and load it into existing nginx installation.
