### ISSUE TITLE
Nothing happens, and connection of client will be aborted.

### ISSUE THREAD

**Issue by valaphee** [ZigzagAK/ngx_zookeeper_lua#3]
Good evening,

I try to use this project as a solution to provide ssl certificates all over my infrastructure with Zookeeper, but unfortunately I don't get any kind of output at all not even in debug.

I just get to know that after entering "ngx.zookeeper.check_completition", the connection stops, and the lua code is no longer executed.

I didn't used the building tool in this repository, because, I am using Openresty's LuaJIT and clone every repository. There was an error during the build process near the if-directive block "#if !defined LUA_VERSION_NUM || LUA_VERSION_NUM < 502", is replaced it with #if false

Hope you can help me in any form, because it is the only project that I found, and I have no time to develop something like this at own.

Kind regards,
Valaphee.

**Comment by ZigzagAK** [comment]
Hello, Valaphee.
Please, send me your build script, problem configuration and zookeeper version.
My email: alkon2000@mail.ru.

**Comment by ZigzagAK** [comment]
Problem is in ssl_certificate_by_lua_block.

```
2019/03/16 20:51:42 [debug] 14819#0: 2019-03-16 20:51:42,243:14819(0x7f53334cb880):ZOO_DEBUG@zoo_awget@3377: Sending request xid=0x5c8d37ad for path [/certs/localhost] to 10.0.0.3:2181
2019/03/16 20:51:42 [debug] 14819#0: *5 event timer add: 0: 1:1552758702244
2019/03/16 20:51:42 [debug] 14819#0: *5 lua ready to sleep for 1 ms
2019/03/16 20:51:42 [debug] 14819#0: *5 lua resume returned 1
2019/03/16 20:51:42 [debug] 14819#0: *5 lua thread yielded
2019/03/16 20:51:42 [debug] 14819#0: *5 http lua finalize fake request: -4, a:1, c:2
2019/03/16 20:51:42 [debug] 14819#0: *5 http lua fake request count:2
2019/03/16 20:51:42 [debug] 14819#0: add cleanup: 0000000000C00148
2019/03/16 20:51:42 [debug] 14819#0: *4 add cleanup: 0000000000C026C8
2019/03/16 20:51:42 [debug] 14819#0: *4 SSL_do_handshake: -1
2019/03/16 20:51:42 [debug] 14819#0: *4 SSL_get_error: 4
2019/03/16 20:51:42 [info] 14819#0: *4 peer closed connection in SSL handshake while loading SSL certificate by lua, client: 127.0.0.1, server: 0.0.0.0:4444
```

This is may be bug of lua-nginx-module.

Workaround:

Try to make caching certificates in ngx.timer.at

1. Turn on zoo caching
```
init_by_lua_block {
  ngx.shared.config:set("zoo.cache.on", true)
  ngx.shared.config:set("zoo.cache.ttl", 3600)
  ngx.shared.config:set("zoo.cache.path.ttl", '[]')
}
```

2. Run timer at init_worker_by_lua_block
```
init_worker_by_lua_block {
  local function job()
    ngx.timer.at(60, function(premature)
      if premature then
        return
      end
      local zoo = require "zoo"
      zoo.tree("/certs")
      zoo.tree("/keys")
      job()
    end)
  end
  job()
}
```
3. zoo.get("/certs/" .. server_name)
Without true second parameter value will be readed from cache.

```
ssl_certificate_by_lua_block {
  local ssl = require "ngx.ssl"
  local zoo = require "zoo"

  local server_name = ssl.server_name()

  local cert = zoo.get("/certs/" .. server_name)
  local key = zoo.get("/keys/" .. server_name)

  if not cert or not key then
    return
  end

  ssl.clear_certs()

  ssl.set_der_cert(ssl.cert_pem_to_der(cert))
  ssl.set_der_priv_key(ssl.priv_key_pem_to_der(key))
}
```

Or you may create your own cache.

**Comment by ZigzagAK** [comment]
See, https://github.com/openresty/lua-nginx-module/issues/694

**Comment by ZigzagAK** [comment]
Problem is resolved.
