### ISSUE TITLE
openrestry version

### ISSUE THREAD

**Issue by klover** [ZigzagAK/ngx_zookeeper_lua#5]
i'm sure.
i'm using an OpenResty release from https://openresty.org/en/download.html
error:

nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file 'lib/resty/core.lua'
        no file './resty/core.lua'
        no file '/usr/local/share/luajit-2.1.0-beta2/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file 'lua/resty/core.lua'
        no file './resty/core.lua'
        no file '/usr/local/share/luajit-2.1.0-beta2/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file 'lib/lua/5.1/resty/core.so'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file 'lib/lua/5.1/resty.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')

**Comment by klover** [comment]
> i'm sure.
> i'm using an OpenResty release from https://openresty.org/en/download.html
> error:
> 
> nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
> nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
> no field package.preload['resty.core']
> no file 'lib/resty/core.lua'
> no file './resty/core.lua'
> no file '/usr/local/share/luajit-2.1.0-beta2/resty/core.lua'
> no file '/usr/local/share/lua/5.1/resty/core.lua'
> no file '/usr/local/share/lua/5.1/resty/core/init.lua'
> no file 'lua/resty/core.lua'
> no file './resty/core.lua'
> no file '/usr/local/share/luajit-2.1.0-beta2/resty/core.lua'
> no file '/usr/local/share/lua/5.1/resty/core.lua'
> no file '/usr/local/share/lua/5.1/resty/core/init.lua'
> no file 'lib/lua/5.1/resty/core.so'
> no file './resty/core.so'
> no file '/usr/local/lib/lua/5.1/resty/core.so'
> no file '/usr/local/lib/lua/5.1/loadall.so'
> no file 'lib/lua/5.1/resty.so'
> no file './resty.so'
> no file '/usr/local/lib/lua/5.1/resty.so'
> no file '/usr/local/lib/lua/5.1/loadall.so')

**Comment by ZigzagAK** [comment]
@klover 
In 2.5.3 build script fixed.
If you are using prebuild openresty you must build this module as dynamic and load it into nginx with load_module directive.

> module 'resty.core' not found

See: https://github.com/openresty/lua-nginx-module#lua_load_resty_core
In latest lua-nginx-module resty.core lua modules loads on default. You may turn off loading it with lua_load_resty_core off.
For examples you may look into latest commit: https://github.com/ZigzagAK/ngx_zookeeper_lua/commit/291427c158a33c4c5bce42c0cdbfa47e11b89e7b
